# Generated by Django 4.0.3 on 2022-04-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='patients',
            new_name='patientTable',
        ),
    ]
