# Generated by Django 4.0.3 on 2022-04-28 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_patients_patienttable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='patientTable',
            new_name='patient',
        ),
    ]
