# Generated by Django 4.0.3 on 2022-05-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rename_patienttable_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient',
        ),
    ]
